# Generated by Django 4.2.6 on 2023-10-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='height_m',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight_kg',
            field=models.FloatField(null=True),
        ),
    ]
